# This is a basic workflow to help you get started with Actions

name: Release on principal Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Unit Test
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Security Sast
        run: |
          echo Add other Test Sast Security
          echo Fortify Test successfull

#  createTag:
#    needs:
#      - release
#    runs-on: ubuntu-latest
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v2
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#        # This token is provided by Actions, you do not need to create your own token
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
#        with:
#          tag_name: ${{ github.run_number }}
#          release_name: Release ${{ github.run_number }}
#          draft: false
#          prerelease: false
  push_adobe:
    needs:
#      - createTag
      - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git Push
        run: |
          git checkout -b test-site-01
          git push https://${{secrets.bnauk_token}}@github.com/benauca/test-adobe-site.git test-site-01
    
